### ISSUE TITLE
Exit trajectory shift incorrect?

### ISSUE THREAD

**Issue by pweigel** [DanielWinklehner/spyral_inflector#3]
Seems like the trajectory for the particle exiting the spiral inflector is shifted incorrectly (see image). There's a possibility it is being track properly (in the right position), but the plotting is incorrect.

![exit_trj](https://user-images.githubusercontent.com/24859204/56512792-62965180-64fe-11e9-93f5-014fd35d6ef1.png)

**Comment by DanielWinklehner** [comment]
This is due to the missing assembly transformations. WIP.

**Comment by pweigel** [comment]
Fixed in https://github.com/DanielWinklehner/spyral_inflector/commit/393aeb35a652f0c09a9e4665dc335da2055d4012.
